# NOTE: This file was generated via generate.sh. Don't edit it directly

name: 'PHP 8.1'

on:
  pull_request:
    paths:
      - 8.1/**
  push:
    paths:
      - 8.1/**

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  verify-templating:
    name: Verify templating
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate
        run: make all
      - name: Check Git status
        run: |
          test -z "$(git status --short)"

  docker:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs:
      - verify-templating
    strategy:
      matrix:
        target:
          [
            "8_1_11-bullseye",
            "8_1_11-buster",
            "8_1_11-alpine3_16",
            "8_1_11-alpine3_15",
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm,arm64
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
      - name: GHCR Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: GHCR build and push
        uses: docker/bake-action@v2
        env:
          REGISTRY: ghcr.io
          REPO: ${{ github.repository_owner }}/laravel-base
        with:
          targets: ${{ matrix.target }}
          set: |
            *.platform=linux/amd64,linux/arm,linux/arm64
          push: ${{ github.event_name == 'push' }}
